### ISSUE TITLE
Unable to install using composer

### ISSUE THREAD

**Issue by peterdutton** [heiglandreas/htmltopdflib#1]
Hi,

I was unable to install this package using the instructions from the readme. It seems that the package is not on packagist at the moment:

![Screenshot from 2020-09-21 11-44-54](https://user-images.githubusercontent.com/942130/93758366-39e91e80-fc00-11ea-9772-f65ce0a5c536.png)

Please let me know if I'm looking in the wrong place. Look forward to trying this out!

**Comment by heiglandreas** [comment]
Thanks for noticing. So far that was only used in our private satis... 

Now the package is available on packagist as well. See https://packagist.org/packages/org_heigl/html-to-pdflib
