### ISSUE TITLE
Class not found when attempting conversion

### ISSUE THREAD

**Issue by peterdutton** [heiglandreas/htmltopdflib#2]
Hi,

When attempting conversion using the library, the classes to provide conversion are not found. I think this is due to an incorrect namespace in the Factory class:
https://github.com/heiglandreas/htmltopdflib/blob/5700040b73c7135b8006790b51369d26d0be07f4/src/Factory.php#L48

I believe this should be ```HtmlToPdflib``` instead of ```HtmlToPdf```.

If there is another way of making this work please let me know. Thanks again!

**Comment by heiglandreas** [comment]
Thanks. I then added a small test to ensure that everything works as expected and fixed that issue. I might as well add a different way of service-detection but that is a later topic ;-)

I also tagged the first release

**Comment by peterdutton** [comment]
@heiglandreas thanks so much for fixing this so quickly! 

I think I am nearly there now, I can run your test without issue on my stack.

Just one question, about the PDFlib macros: should these be supplied separately, or does the library generate them? I refer to the macro such as:
`<macro {
    bold {fontname=Helvetica fontsize=12 encoding=winansi}
    bolditalic {fontname=Helvetica fontsize=8 encoding=winansi}
    italic {fontname=Helvetica fontsize=8 encoding=winansi}
}>`

Thanks

**Comment by heiglandreas** [comment]
You're welcome @peterdutton :wink:

The Macros need to be provided by you. As they depend so much on your local setup (which fonts to use, what fontsize, linewidth etc) it doesn't really make sense to have them autogenerated.
